// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sweet-go/stdlib/worker (interfaces: Client)

// Package worker_mock is a generated GoMock package.
package worker_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// EnqueueTask mocks base method.
func (m *MockClient) EnqueueTask(arg0 context.Context, arg1 *asynq.Task) (*asynq.TaskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueTask", arg0, arg1)
	ret0, _ := ret[0].(*asynq.TaskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueTask indicates an expected call of EnqueueTask.
func (mr *MockClientMockRecorder) EnqueueTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueTask", reflect.TypeOf((*MockClient)(nil).EnqueueTask), arg0, arg1)
}
